import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

/**
 * The Epic 019 type scale lives in the token JSON (primitive + semantic) and is
 * regenerated by Style Dictionary — never hand-edited into tokens.css. These
 * tests assert the scale exists there, that the name is the dominant step, and
 * that the muted-small text tier clears WCAG AA on the card surface.
 */
const primitive = JSON.parse(readFileSync('tokens/primitive.json', 'utf8'))
const semantic = JSON.parse(readFileSync('tokens/semantic.json', 'utf8'))

const rem = (token: { $value: string }): number => Number.parseFloat(token.$value)

describe('type scale is authored as tokens (AC-19.2.1)', () => {
  const roles = ['name', 'verdict', 'fact-value', 'fact-label', 'condition', 'supporting'] as const

  it('every card role has a semantic type token that references a primitive size', () => {
    for (const role of roles) {
      const t = semantic.type[role]
      expect(t, role).toBeTruthy()
      // Semantic size REFERENCES a primitive size step (outputReferences keeps the
      // generated var a var(--size-*), never a hardcoded rem).
      expect(t.size.$value, role).toMatch(/^\{size\.[a-z-]+\}$/)
      const primName = t.size.$value.slice('{size.'.length, -1)
      expect(primitive.size[primName], `${role} -> ${primName}`).toBeTruthy()
    }
  })

  it('the generated tokens.css is not hand-edited (auto-generated banner intact)', () => {
    const css = readFileSync('src/design/tokens.css', 'utf8')
    expect(css).toContain('Do not edit directly, this file was auto-generated.')
    // The new semantic vars are present (proof the pipeline ran, not a manual edit).
    expect(css).toContain('--type-name-size: var(--size-name);')
  })
})

describe('the name is the dominant type on the card (AC-19.2.2)', () => {
  it('size.name is strictly larger than every other card text size', () => {
    const name = rem(primitive.size.name)
    const others = ['verdict', 'fact-value', 'fact-label', 'condition', 'supporting'] as const
    for (const role of others) {
      expect(name, `name vs ${role}`).toBeGreaterThan(rem(primitive.size[role]))
    }
  })
})

describe('muted-small text clears WCAG AA on the card (AC-19.2.3)', () => {
  // Relative luminance + contrast ratio per WCAG 2.x.
  const channel = (c: number): number => {
    const s = c / 255
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4
  }
  const luminance = (hex: string): number => {
    const n = Number.parseInt(hex.replace('#', ''), 16)
    const r = channel((n >> 16) & 0xff)
    const g = channel((n >> 8) & 0xff)
    const b = channel(n & 0xff)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b
  }
  const contrast = (a: string, b: string): number => {
    const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x)
    return (hi + 0.05) / (lo + 0.05)
  }

  it('text-muted on surface-raised (the card ground) is >= 4.5:1', () => {
    // Resolve the semantic refs down to primitive hex.
    const muted = primitive.color.neutral['500'].$value // text.muted
    const raised = primitive.color.neutral['25'].$value // surface.raised
    expect(contrast(muted, raised)).toBeGreaterThanOrEqual(4.5)
  })
})
